apiVersion: v1
kind: Service
metadata:
    name: "wubot2-1341"
    labels:
        app: "wubot2-1341"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "wubot2-1341"